export const APPLICATION_CORE = 'api-core';
export const APPLICATION_GATEWAY = 'api-gateway';

export const APPLICATIONS = [APPLICATION_GATEWAY, APPLICATION_CORE];

export const DEFAULT_APPLICATION = APPLICATION_GATEWAY;
