export const ACTIVATE_SUBSCRIPTION = 'ACTIVATE_SUBSCRIPTION';
export const ATTACH_ROUTINE = 'ATTACH_ROUTINE';
export const ATTACH_ROUTINE_USER_TECHNICAL_SHEET = 'ATTACH_ROUTINE_USER_TECHNICAL_SHEET';
export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_TO_DEPLOY_ROUTINE = 'CHANGE_TO_DEPLOY_ROUTINE';
export const CHANGE_TO_DRAFT_ROUTINE = 'CHANGE_TO_DRAFT_ROUTINE';
export const CREATE_BLOG = 'CREATE_BLOG';
export const CREATE_CURRENCY = 'CREATE_CURRENCY';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const CREATE_MUSCLE_GROUP = 'CREATE_MUSCLE_GROUP';
export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_SPECIFICATION = 'CREATE_PLAN_SPECIFICATION';
export const CREATE_PLAN_VARIANT = 'CREATE_PLAN_VARIANT';
export const CREATE_ROUTINE = 'CREATE_ROUTINE';
export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const CREATE_USER_ROUTINE = 'CREATE_USER_ROUTINE';
export const CREATE_USER_TECHNICAL_SHEET = 'CREATE_USER_TECHNICAL_SHEET';
export const CREATE_VIDEO = 'CREATE_VIDEO';
export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_MUSCLE_GROUP = 'DELETE_MUSCLE_GROUP';
export const DELETE_PLAN = 'DELETE_PLAN';
export const DELETE_PLAN_SPECIFICATION = 'DELETE_PLAN_SPECIFICATION';
export const DELETE_PLAN_VARIANT = 'DELETE_PLAN_VARIANT';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
export const DELETE_USER_ROUTINE = 'DELETE_USER_ROUTINE';
export const DELETE_USER_TECHNICAL_SHEET = 'DELETE_USER_TECHNICAL_SHEET';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const DETACH_ROUTINE = 'DETACH_ROUTINE';
export const DETACH_ROUTINE_USER_TECHNICAL_SHEET = 'DETACH_ROUTINE_USER_TECHNICAL_SHEET';
export const INCREMENT_DUE_DATE_SUBSCRIPTION = 'INCREMENT_DUE_DATE_SUBSCRIPTION';
export const PAUSE_SUBSCRIPTION = 'PAUSE_SUBSCRIPTION';
export const PUBLISH_BLOG = 'PUBLISH_BLOG';
export const UNPUBLISH_BLOG = 'UNPUBLISH_BLOG';
export const UPDATE_BLOG = 'UPDATE_BLOG';
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const UPDATE_MUSCLE_GROUP = 'UPDATE_MUSCLE_GROUP';
export const UPDATE_MY_ON_BOARDING_STATUS = 'UPDATE_MY_ON_BOARDING_STATUS';
export const UPDATE_MY_USER_PROFILE = 'UPDATE_MY_USER_PROFILE';
export const UPDATE_ON_BOARDING_STATE = 'UPDATE_ON_BOARDING_STATE';
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const UPDATE_PLAN_SPECIFICATION = 'UPDATE_PLAN_SPECIFICATION';
export const UPDATE_PLAN_VARIANT = 'UPDATE_PLAN_VARIANT';
export const UPDATE_ROUTINE = 'UPDATE_ROUTINE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_ROUTINE = 'UPDATE_USER_ROUTINE';
export const UPDATE_USER_TECHNICAL_SHEET = 'UPDATE_USER_TECHNICAL_SHEET';

export const ACTIONS_LIST = [
  ACTIVATE_SUBSCRIPTION,
  ATTACH_ROUTINE,
  ATTACH_ROUTINE_USER_TECHNICAL_SHEET,
  CANCEL_SUBSCRIPTION,
  CHANGE_PASSWORD,
  CHANGE_TO_DEPLOY_ROUTINE,
  CHANGE_TO_DRAFT_ROUTINE,
  CREATE_BLOG,
  CREATE_CURRENCY,
  CREATE_EXERCISE,
  CREATE_MUSCLE_GROUP,
  CREATE_PLAN,
  CREATE_PLAN_SPECIFICATION,
  CREATE_PLAN_VARIANT,
  CREATE_ROUTINE,
  CREATE_SUBSCRIPTION,
  CREATE_USER_ROUTINE,
  CREATE_USER_TECHNICAL_SHEET,
  CREATE_VIDEO,
  DELETE_BLOG,
  DELETE_CURRENCY,
  DELETE_EXERCISE,
  DELETE_MUSCLE_GROUP,
  DELETE_PLAN,
  DELETE_PLAN_SPECIFICATION,
  DELETE_PLAN_VARIANT,
  DELETE_ROUTINE,
  DELETE_SUBSCRIPTION,
  DELETE_USER_ROUTINE,
  DELETE_USER_TECHNICAL_SHEET,
  DELETE_VIDEO,
  DETACH_ROUTINE,
  DETACH_ROUTINE_USER_TECHNICAL_SHEET,
  INCREMENT_DUE_DATE_SUBSCRIPTION,
  PAUSE_SUBSCRIPTION,
  PUBLISH_BLOG,
  UNPUBLISH_BLOG,
  UPDATE_BLOG,
  UPDATE_CURRENCY,
  UPDATE_EXERCISE,
  UPDATE_MUSCLE_GROUP,
  UPDATE_MY_ON_BOARDING_STATUS,
  UPDATE_MY_USER_PROFILE,
  UPDATE_ON_BOARDING_STATE,
  UPDATE_PLAN,
  UPDATE_PLAN_SPECIFICATION,
  UPDATE_PLAN_VARIANT,
  UPDATE_ROUTINE,
  UPDATE_USER_PROFILE,
  UPDATE_USER_ROUTINE,
  UPDATE_USER_TECHNICAL_SHEET,
];
